name: Release
on:
  push:
    tags:
      - 'v*'

jobs:

  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: Install snapcraft
      run: sudo snap install snapcraft --classic
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SNAPCRAFT_BUILD_ENVIRONMENT: host
      run: npm run publish
    - name: artifact
      uses: actions/upload-artifact@v2
      with:
        name: snap
        path: out/make/*.snap
    - uses: snapcore/action-publish@v1
      value: `ls out/make/*.snap`
      with:
        store_login: ${{ secrets.SNAP_STORE_LOGIN }}
        snap: $value
        release: stable

  publish_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish

  publish_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish
